Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:6928][64396] Child process with pid: 64532 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python312/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'django_summernote'
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python312/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'django_summernote'
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/attenuhm/main_app/passenger_wsgi.py", line 15, in <module>
    from core.wsgi import application
  File "/home/attenuhm/main_app/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/attenuhm/virtualenv/main_app/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /favicon.ico
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /media/images/google-deepmind-Oy2yXvl1WLg-unsplash.jpg
Not Found: /dashboard4323
Not Found: /dashboard/232
